[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Pengaturan Header dan Cache untuk Performa Maksimal di Netlify CDN
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
